### ISSUE TITLE
"Favorite" star vanishes on meta SO with the latest SOUP

### ISSUE THREAD

**Issue by Hunter-Github** [vyznev/soup#24]
Firefox ESR here.

![SOUP1](https://i.stack.imgur.com/511zy.png)

**Comment by vyznev** [comment]
Thanks for the report! I'm unable to reproduce this on Firefox 44.0, but I'm 99.9% sure I know which fix is causing it. Since the [issue](http://meta.stackoverflow.com/questions/306325/the-yellow-star-in-the-sprites-svg-image-looks-unfinished) it fixes is completely trivial, I've disabled the fix while I look into this. Just to confirm, can you check if this problem still happens with SOUP v1.44.1 (just released; you may need to manually update SOUP if the auto-update hasn't kicked in yet)?

**Comment by Hunter-Github** [comment]
Fixed.
