### ISSUE TITLE
Ctrl+L in editor broken when SOUP is enabled.

### ISSUE THREAD

**Issue by DavidPostill** [vyznev/soup#27]
Windows 7 Home Premium 64 bit, Firefox 49.0.1

SOUP 1.44.2

<kbd>OK</kbd> and <kbd>Cancel</kbd> not longer work when using <kbd>Ctrl</kbd><kbd>L</kbd> in the editor to enter a hyperlink.

The following error is generated:

![screenshot - 01_10_2016 17_11_17](https://cloud.githubusercontent.com/assets/7079224/19015346/af221ee6-87fa-11e6-8d10-71fbb2953edc.png)

![screenshot - 01_10_2016 17_12_34](https://cloud.githubusercontent.com/assets/7079224/19015349/b5f55aa8-87fa-11e6-8e35-28f1faa463ba.png)

Works fine if SOUP is disabled.

Consequence of [We have updated jQuery to 1.12.4 - please report related bugs here](https://meta.stackexchange.com/questions/284996/we-have-updated-jquery-to-1-12-4-please-report-related-bugs-here)?

**Comment by vyznev** [comment]
Thanks for the repory. I'm on mobile right now, but I'll try to fix this tomorrow.

**Comment by vyznev** [comment]
This was an issue with the [international domain name fix (mse234680)](http://meta.stackexchange.com/questions/234680/domain-names-in-an-url-are-incorrectly-encoded-as-escaped-ascii-characters-inste), and it should be fixed in SOUP 1.44.3 (and v1.45.18 devel) released today. BTW, while testing this, I also noticed a couple of other issues with the same code -- notably, that it completely fails to do anything with the new-style link entry dialog used on SO. I'll try to fix that for SOUP 1.46.
