### ISSUE TITLE
Small space is added between comments and timestamps

### ISSUE THREAD

**Issue by Sir-Cumference** [vyznev/soup#30]
Small bug, but I thought I'd mention it. Normally, the comments look like this:
<img width="636" alt="screen shot 2017-08-03 at 1 37 14 pm" src="https://user-images.githubusercontent.com/5375326/28934986-eb85f820-7850-11e7-9bcf-99b64207d67a.png">

However SOUP adds an extra space between the comment and the dash:
<img width="625" alt="screen shot 2017-08-03 at 1 37 04 pm" src="https://user-images.githubusercontent.com/5375326/28934998-f86ba2a6-7850-11e7-99a0-e2659a604843.png">

This causes the timestamps to shift a bit when the page loads.

**Comment by vyznev** [comment]
Thanks for the report!

The extra space is actually a deliberate feature, to make the signature stand off just a little bit from the comment text. But you've got a point that the shifting can be a bit distracting too. I probably should either remove the extra space or find a way to eliminate the delay before the fix is applied.

In any case, that fix apparently doesn't do what it's primarily meant to do (i.e. prevent wrapping between the dash and the signature) consistently on all browsers, so I really need to revisit it anyway in some upcoming SOUP version.

**Comment by vyznev** [comment]
This should be fixed in SOUP 1.54. While tweaking the fix to make it work correctly on Chrome, I decided to simply remove the extra space to avoid any unnecessary layout jumps.
