### ISSUE TITLE
Document future of Greasemonkey support

### ISSUE THREAD

**Issue by reitzig** [vyznev/soup#31]
As I'm sure you're aware, [Greasemonkey 4](https://www.greasespot.net/2017/09/greasemonkey-4-announcement.html), due to release with FF 57, is not backwards compatible. Scripts will need to be adapted.

Please document which of the following options for Greasemonkey <4 users will be open regarding SOUP:

 1. SOUP will be ported to Greasemonkey 4.
 2. SOUP will no longer be support Greasemonkey; use Tampermonkey (or...?).
 3. SOUP will no longer be support Firefox as a userscript; use the browser extension.

**Comment by vyznev** [comment]
As far as I'm aware, SOUP should in fact be compatible with GM4 as it is, since it does not use the `GM_*` API or `unsafeWindow`. That said, I should indeed test that and document the results, since I'm sure you're not the only one with that question.

**Comment by vyznev** [comment]
I've tested SOUP with GM4, and it indeed works just fine, except for a few issues caused by known FF57 / GM4 bugs. I've worked around most of those issues, although the bug that [prevents script installation from GitHub](https://github.com/greasemonkey/greasemonkey/issues/2631) is not something I can do much about. (I *could* provide an alternative installation source for GM4 users, but it's probably easier to just recommend the stand-alone version of SOUP instead.) Anyway, the [SOUP StackApps page](https://stackapps.com/questions/4486/the-stack-overflow-unofficial-patch-soup) already describes the current state of GM4 support, and I expect that, once GM4 stabilizes properly, it should continue to run SOUP just fine.
