### ISSUE TITLE
User avatars appear in wrong spot on Microsoft Edge

### ISSUE THREAD

**Issue by gparyani** [vyznev/soup#32]
In Microsoft Edge, running the latest stable version of SOUP in Tampermonkey, the user avatars appear in the wrong spot, below where they should be:

![avatar appears below where it should be](https://user-images.githubusercontent.com/6440487/35346770-b89b46e6-00f8-11e8-8856-3178acbf50fc.PNG)

[Question where this screenshot was taken](https://meta.stackexchange.com/questions/305886/why-isnt-comments-are-not-for-extended-discussion-the-case-on-meta)

**Comment by vyznev** [comment]
Thanks. Just to check, do you still see this behavior on SOUP v1.50 (released yesterday)? I don't see anything obvious in the changelog that might've affected this, but it's worth checking before I start chasing false trails. I still haven't actually managed to test this on Edge, but I was hoping I could at least narrow down the list of fixes that could cause it.

**Comment by vyznev** [comment]
BTW, if you don't mind playing with the source code, you could help me narrow this down. Most of the [SOUP source code](https://github.com/vyznev/soup/blob/master/SOUP.user.js) consists of individual [fix entries](https://github.com/vyznev/soup/wiki/Adding-a-new-fix) of the form `fixes.someid123 = { ... }`. If you want, you could open the SOUP source code in the Tampermonkey dashboard, remove a bunch of those fix entries and see if the problem still persists. (Of course, remember to Ctrl+S and reload the page.) Repeat until it does, then undo the last step and remove something else. Eventually, you should be able to narrow it down to a single fix entry (or possibly two that interact in some weird way).

Then just let me know the ID of the entry. My guess would be that it's *probably* one of the CSS-only fixes near the top of the code, since this looks like a CSS problem, but I can't be sure.

**Comment by gparyani** [comment]
This does happen on v1.50.0. I'll check which fix(es) trigger it and post another reply in a while.

**Comment by gparyani** [comment]
And it looks like `mse84296` is causing the issue. I commented that out and the avatars show normally.

**Comment by vyznev** [comment]
Thanks again! There's actually no real reason for the mse84296 CSS rule to apply to the avatars, so if that's the only issue, excluding them ought to be doable. That said, while you're at it, could you please also check if [this Safari bug](https://meta.stackoverflow.com/questions/275151/missing-space-bug-in-comments-on-osx) (or something similar) occurs on Edge with SOUP (and the mse84296 fix) enabled?

**Comment by vyznev** [comment]
Can you try [installing SOUP v1.51.4 from the development branch](https://github.com/vyznev/soup/raw/devel/SOUP.user.js) and see if this issue persists? If it does, I can add a more explicit rule to exclude avatars from the bidi style, but I figured I'd first see if just [removing the fallbacks](https://github.com/vyznev/soup/commit/055fe3e418b68d79b688f6d269a8a24c58a5b712#diff-1577392c0b6ec33553046eb648fb1bd8) would help.

**Comment by gparyani** [comment]
No, the Safari bug does not occur on Edge with the current version of the patch.

The development branch correctly fixes the avatar bug in Edge. Thank you very much!

**Comment by vyznev** [comment]
Thanks! I'll mark this as resolved. The updated CSS without the fallbacks will be included in the next stable SOUP release (v1.52).
