### ISSUE TITLE
Request: fix the Chat FAQ page

### ISSUE THREAD

**Issue by mjpieters** [vyznev/soup#33]
See https://meta.stackoverflow.com/questions/362554/why-are-the-chat-faq-in-almost-identical-links-different; the page tries to use `$.curCSS()` which is gone from jQuery.

Could S.O.U.P. provide a shim; (such as the one [provided here](https://stackoverflow.com/questions/29298462/c-curcss-is-not-a-function-bug-from-jquery))?

**Comment by vyznev** [comment]
[Done.](https://github.com/vyznev/soup/commit/4b0a0e1c7fc9ba815eb4822f60e652d6898b2072#diff-1577392c0b6ec33553046eb648fb1bd8) Unfortunately, it doesn't work reliably (or, as far as I can tell, at all) on Chrome + Tampermonkey due to [a race condition](https://github.com/Tampermonkey/tampermonkey/issues/211) in TM's script loading. But it works fine on Firefox + Violentmonkey and on Chrome as a stand-alone extension, so I'm calling it good enough. :P

**Comment by vyznev** [comment]
Looks like setting Injection Mode to "Instant" in Tampermonkey prefs (under Experimental) is also enough to make this work.
