### ISSUE TITLE
Request for new fix for pagination links for spam-deleted posts

### ISSUE THREAD

**Issue by gparyani** [vyznev/soup#43]
I recently encountered a bug when viewing a post with multiple pages of answers that a moderator had locked and deleted, which had helpful spam or rude/abusive flags.

When trying to navigate to a subsequent page of answers using the pagination link, or when trying to access a specific answer that happens to be on a page other than the first page, the server-side logic that automatically removes the question title from the URL (to prevent it from being exploited by spammers) also causes things like `?page=2` to be stripped out, making it impossible to view a subsequent page unless I manually modify the URL to remove the question title while leaving the query parameter intact.

I've posted a [detailed answer](https://meta.stackexchange.com/questions/322619/cant-see-other-pages-of-answers-on-a-certain-deleted-question/322621#322621) showing the cause of the bug and the workaround.

It would be nice to have the fix in SOUP. I think it's reasonable because all that needs to be done is remove the question title from the pagination links for deleted posts. (The "Return to Answer" links may not be fixable, but still.)

**Comment by gparyani** [comment]
@vyznev Is this being considered?

**Comment by vyznev** [comment]
As you may have noticed, I haven't had much time for SOUP development lately. I'd be happy to accept any contributions, but writing new fixes from scratch takes time that I often don't really have.

That said, since you reminded me of this, I decided to take a look into this issue, and it turns out to be fairly easy to work around. So, [here you go.](https://github.com/vyznev/soup/commit/55927e10160fd8b627340ed0cf38149632461d6f#diff-1577392c0b6ec33553046eb648fb1bd8) The fix is already in the development branch of SOUP, and will be in the next stable release. :)
