### ISSUE TITLE
Feature request: implement mse341498 fix (spoilers in user profiles)

### ISSUE THREAD

**Issue by gparyani** [vyznev/soup#49]
I recently filed [mse341498](https://meta.stackexchange.com/questions/341498/spoilers-in-user-profiles-dont-show-permanently-once-they-are-clicked-unlike-f), which reports that spoilers in user profiles don't continue to show when they are clicked, which contradicts the expected behavior for posts.

Can a client-side workaround for this please be implemented in SOUP?

**Comment by vyznev** [comment]
I'll take a look at it. I suspect this happens everywhere that supports spoiler markup other than in posts, since the JS code to inject the click handlers isn't run.

In principle, just adding the missing click handlers should do the trick. It might be good idea to add some defensive code to make sure that we don't end up injecting duplicate click handlers if SE ever fixes this bug on their end, though.

**Comment by vyznev** [comment]
Fixed in v1.57.9 (commit 6af4e39) on the devel branch. And I really should make a new stable release soon.
